version: '3.7'
services:

    mongo-prod: 
        container_name: mongo-prod
        volumes:
            - '/var/lib/mongodb:/data/db'
            - '${DATA_FOLDER}/mongo-dumps:/mongo-dumps'
            - '${INSTANCE_FOLDER}/mongo-scripts:/mongo-scripts'
            - '${INSTANCE_FOLDER}/mongod.conf:/etc/mongod.conf'
        command: mongod --config /etc/mongod.conf
        ports:
            - '27017:27017'
        env_file: 
            - '../secrets/mongo.env'
        networks:
            - net-prod
        # Always specify version of mongo. When it upgrades automatically there can be database issues that need to be resolved
        # and we don't want that happening unexpectedly
        image: mongo:4.0

# https://docs.docker.com/compose/networking/

networks:
  net-prod:
    driver: bridge
    external: false
    name: net-prod

# To force compose to use an externally pre-created network outside this compose file you can do this
# networks:
#   default:
#     external:
#       name: my-pre-existing-network
